import { expect, test } from '@playwright/test'

test('registers, saves a scenario, and exposes saved item controls', async ({ page }) => {
  const email = `e2e-${Date.now()}-${crypto.randomUUID()}@example.com`
  const password = 'correct-horse-battery-staple'

  await page.setViewportSize({ width: 1280, height: 1000 })
  await page.goto('/')
  await page.getByRole('tab', { name: 'Create account' }).click()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: /Create my workspace/ }).click()

  await expect(page.getByRole('heading', { name: 'Projection', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByRole('tab', { name: 'Sign in' }).click()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: /Sign in to cashflow/ }).click()
  await expect(page.getByRole('heading', { name: 'Projection', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add item/ }).click()

  const itemForm = page.locator('form.item-form')
  await expect(itemForm.getByRole('heading', { name: 'Start your account' })).toBeVisible()
  await itemForm.getByLabel('Starting balance').fill('50')
  await itemForm.getByLabel('Name').fill('Card payment')
  await itemForm.getByLabel('Amount').fill('100')
  await itemForm.getByLabel('First date').fill('2026-08-24')
  await itemForm.getByLabel('Flexibility').selectOption('WINDOW')
  await itemForm.getByLabel('Window start').fill('24')
  await itemForm.getByLabel('Window end').fill('28')
  await itemForm.getByRole('button', { name: 'Save and project' }).click()

  await expect(page.getByText('Card payment').first()).toBeVisible()
  const projectionPanel = page.locator('section.projection-panel').first()
  await expect(projectionPanel.getByRole('heading', { name: '90-day projection' })).toBeVisible()
  await expect(projectionPanel.locator('svg[aria-label="Projected balance line chart"]')).toBeVisible()

  await page.getByRole('button', { name: /Add item/ }).click()
  const incomeForm = page.locator('form.item-form')
  await incomeForm.getByRole('button', { name: 'Income', exact: true }).click()
  await incomeForm.getByLabel('Name').fill('Paycheck')
  await incomeForm.getByLabel('Amount').fill('900')
  await incomeForm.getByLabel('First date').fill('2026-08-25')
  await incomeForm.getByRole('button', { name: 'Save and project' }).click()

  await expect(page.getByText('Paycheck')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Consider this scheduling move' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Apply recommendation' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Apply recommendation' }).first().click()
  await expect(page.getByText(/Applied as a hypothetical schedule change for Card payment/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo change' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Undo change' }).first().click()
  await expect(page.getByText(/Applied as a hypothetical schedule change for Card payment/)).toBeHidden()
  await expect(page.getByRole('button', { name: 'Apply recommendation' }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Bills', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Bills', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit Card payment' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause Card payment' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Delete Card payment' })).toBeVisible()
  await page.getByRole('button', { name: 'Pause Card payment' }).click()
  await expect(page.getByRole('button', { name: 'Resume Card payment' })).toBeVisible()
  await page.getByRole('button', { name: 'Resume Card payment' }).click()
  await expect(page.getByRole('button', { name: 'Pause Card payment' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Card payment' }).click()
  await expect(page.getByRole('heading', { name: 'Edit item' })).toBeVisible()
  await page.locator('form.item-form').getByLabel('Amount').fill('110')
  await page.locator('form.item-form').getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByText('Changes saved to your account').first()).toBeVisible()
  await page.getByRole('button', { name: 'Delete Card payment' }).click()
  await expect(page.getByRole('dialog', { name: /Delete Card payment/ })).toContainText('remove future occurrences from the projection')
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('button', { name: 'Edit Card payment' })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Card payment' }).click()
  await page.getByRole('button', { name: 'Delete item' }).click()
  await expect(page.getByRole('button', { name: 'Edit Card payment' })).toBeHidden()

  await page.getByRole('button', { name: 'Income', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Income', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit Paycheck' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pause Paycheck' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Delete Paycheck' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Paycheck' }).click()
  await expect(page.getByRole('heading', { name: 'Edit item' })).toBeVisible()
  await page.locator('form.item-form').getByLabel('Amount').fill('910')
  await page.locator('form.item-form').getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByText('Changes saved to your account').first()).toBeVisible()
  await page.getByRole('button', { name: 'Delete Paycheck' }).click()
  await expect(page.getByRole('dialog', { name: /Delete Paycheck/ })).toContainText('remove future occurrences from the projection')
  await page.getByRole('button', { name: 'Delete item' }).click()
  await expect(page.getByRole('button', { name: 'Edit Paycheck' })).toBeHidden()
})